import { useState, type ChangeEvent, type FormEvent } from 'react'
import { ArrowLeft, ImagePlus, Save, Star, Ticket, X } from 'lucide-react'
import { fileToDataUrl } from '../../lib/images'
import type { DiaryDraft, DiaryEntry, ViewingMode } from '../../types/diary'
import type { NbaGame, PlayerSpotlight } from '../../types/nba'
interface Props { games: NbaGame[]; players: PlayerSpotlight[]; entry?: DiaryEntry; onSave: (draft: DiaryDraft) => void; onBack: () => void }
const modes: { value: ViewingMode; label: string }[] = [{value:'HOME',label:'집관'},{value:'ARENA',label:'직관'},{value:'PUB',label:'스포츠 펍'},{value:'POPUP',label:'팝업'}]
function draftFor(game: NbaGame): DiaryDraft { return { gameId:game.id, gameDate:game.date, favoriteTeam:game.homeTeam.name, opponentTeam:game.awayTeam.name, homeScore:game.homeScore, awayScore:game.awayScore, result:game.status === 'UPCOMING' ? 'UPCOMING' : 'WIN', viewingMode:'HOME', venue:'', favoritePlayer:'', rating:5, mood:'짜릿함', note:'', photos:[] } }
export function DiaryForm({ games, players, entry, onSave, onBack }: Props) { const [draft, setDraft] = useState<DiaryDraft>(entry ?? draftFor(games[0])); const [error,setError] = useState(''); const change = <K extends keyof DiaryDraft>(key:K,value:DiaryDraft[K]) => setDraft(prev => ({...prev,[key]:value})); const selectGame = (event: ChangeEvent<HTMLSelectElement>) => { const game = games.find(item => item.id === event.target.value); if (game) setDraft(prev => ({...draftFor(game), photos:prev.photos, ticketImage:prev.ticketImage, note:prev.note, rating:prev.rating, mood:prev.mood, favoritePlayer:prev.favoritePlayer, viewingMode:prev.viewingMode })) }
 const addImages = async (event: ChangeEvent<HTMLInputElement>, ticket=false) => { const files = Array.from(event.target.files ?? []); try { if (!ticket && draft.photos.length + files.length > 3) throw new Error('사진은 최대 3장까지 첨부할 수 있어요.'); const values = await Promise.all(files.map(fileToDataUrl)); if (ticket) change('ticketImage', values[0]); else change('photos', [...draft.photos,...values]); setError('') } catch (e) { setError(e instanceof Error ? e.message : '이미지를 추가하지 못했어요.') } finally { event.target.value='' } }
 const submit=(event:FormEvent)=>{event.preventDefault(); if(!draft.gameDate||!draft.favoriteTeam||!draft.opponentTeam||!draft.rating){setError('경기, 응원 팀, 평점은 꼭 입력해 주세요.');return} onSave(draft)}
 return <section className="screen form-screen"><button className="back-button" onClick={onBack}><ArrowLeft size={18}/> 돌아가기</button><p className="eyebrow">GAME NIGHT LOG</p><h1>{entry?'관람 일기 수정':'관람 일기 쓰기'}</h1><p className="screen-subtitle">실제 경기와 오늘의 기억을 한 장에 남겨 보세요.</p><form onSubmit={submit} className="diary-form"><label>경기 선택<select value={draft.gameId} onChange={selectGame}>{games.map(game=><option key={game.id} value={game.id}>{game.date} · {game.homeTeam.name} vs {game.awayTeam.name}</option>)}</select></label><div className="form-grid"><label>응원 팀<input value={draft.favoriteTeam} onChange={e=>change('favoriteTeam',e.target.value)}/></label><label>상대 팀<input value={draft.opponentTeam} onChange={e=>change('opponentTeam',e.target.value)}/></label></div><div className="form-grid"><label>관람 방식<select value={draft.viewingMode} onChange={e=>change('viewingMode',e.target.value as ViewingMode)}>{modes.map(mode=><option key={mode.value} value={mode.value}>{mode.label}</option>)}</select></label><label>장소<input placeholder="우리 집, 경기장 이름 등" value={draft.venue ?? ''} onChange={e=>change('venue',e.target.value)}/></label></div>{draft.viewingMode==='ARENA'&&<label>좌석<input value={draft.seat ?? ''} onChange={e=>change('seat',e.target.value)} placeholder="예: 2층 A구역"/></label>}<label>오늘의 최애 선수<select value={draft.favoritePlayer ?? ''} onChange={e=>change('favoritePlayer',e.target.value)}><option value="">선택 안 함</option>{players.map(player=><option key={player.id}>{player.name}</option>)}</select></label><fieldset><legend>평점</legend><div className="rating-row">{[1,2,3,4,5].map(value=><button type="button" aria-label={`${value}점`} className={value<=draft.rating?'selected':''} onClick={()=>change('rating',value)} key={value}><Star size={24} fill={value<=draft.rating?'currentColor':'none'}/></button>)}</div></fieldset><label>감정<input value={draft.mood ?? ''} onChange={e=>change('mood',e.target.value)} placeholder="예: 짜릿함"/></label><label>한 줄 감상<textarea value={draft.note ?? ''} onChange={e=>change('note',e.target.value)} placeholder="오늘 경기는 왜 기억에 남았나요?" rows={4}/></label><div className="upload-block"><b>직접 촬영한 사진 <small>최대 3장 · 1.5MB 이하</small></b><label className="upload-button"><ImagePlus size={18}/> 사진 첨부<input type="file" accept="image/*" multiple onChange={e=>addImages(e)}/></label><Preview images={draft.photos} onRemove={index=>change('photos',draft.photos.filter((_,i)=>i!==index))}/></div><div className="upload-block"><b>티켓 이미지 <small>선택 · 1장</small></b><p className="privacy">QR 코드, 바코드, 예매 번호가 보이지 않는지 확인해 주세요.</p><label className="upload-button"><Ticket size={18}/> 티켓 첨부<input type="file" accept="image/*" onChange={e=>addImages(e,true)}/></label>{draft.ticketImage&&<Preview images={[draft.ticketImage]} onRemove={()=>change('ticketImage',undefined)}/>}</div>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary-button" type="submit"><Save size={18}/> 일기 저장하기</button></form></section> }
function Preview({images,onRemove}:{images:string[];onRemove:(index:number)=>void}) { return <div className="preview-row">{images.map((image,index)=><div className="preview" key={image.slice(-16)}><img src={image} alt={`첨부 이미지 ${index+1}`}/><button type="button" aria-label="첨부 이미지 삭제" onClick={()=>onRemove(index)}><X size={14}/></button></div>)}</div> }
